[2023-09-04T12:41:08.705+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-08-11T00:00:00+00:00/task_id=accurate permission to 509
[2023-09-04T12:41:09.124+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-08-11T00:00:00+00:00/task_id=accurate permission to 509
[2023-09-04T12:41:10.110+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.accurate scheduled__2023-08-11T00:00:00+00:00 [queued]>
[2023-09-04T12:41:10.262+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.accurate scheduled__2023-08-11T00:00:00+00:00 [queued]>
[2023-09-04T12:41:10.280+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-04T12:41:10.407+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): accurate> on 2023-08-11 00:00:00+00:00
[2023-09-04T12:41:10.430+0000] {standard_task_runner.py:57} INFO - Started process 104 to run task
[2023-09-04T12:41:10.467+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2023-08-11T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpetthcz4f']
[2023-09-04T12:41:10.485+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask accurate
[2023-09-04T12:41:10.848+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-08-11T00:00:00+00:00/task_id=accurate permission to 509
[2023-09-04T12:41:10.862+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.accurate scheduled__2023-08-11T00:00:00+00:00 [running]> on host 0ff7fa45765f
[2023-09-04T12:41:11.692+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='accurate' AIRFLOW_CTX_EXECUTION_DATE='2023-08-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-11T00:00:00+00:00'
[2023-09-04T12:41:11.701+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-04T12:41:11.712+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'accurate"]
[2023-09-04T12:41:11.764+0000] {subprocess.py:86} INFO - Output:
[2023-09-04T12:41:11.793+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-04T12:41:11.799+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-04T12:41:11.801+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-04T12:41:11.932+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-04T12:41:11.977+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=accurate, execution_date=20230811T000000, start_date=20230904T124110, end_date=20230904T124111
[2023-09-04T12:41:12.055+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 53 for task accurate (Bash command failed. The command returned a non-zero exit code 2.; 104)
[2023-09-04T12:41:12.111+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-04T12:41:12.237+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
