[2023-08-09T08:30:41.556+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=manual__2023-08-09T08:30:17.385813+00:00/task_id=accurate permission to 509
[2023-08-09T08:30:41.645+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=manual__2023-08-09T08:30:17.385813+00:00/task_id=accurate permission to 509
[2023-08-09T08:30:42.123+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.accurate manual__2023-08-09T08:30:17.385813+00:00 [queued]>
[2023-08-09T08:30:42.157+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.accurate manual__2023-08-09T08:30:17.385813+00:00 [queued]>
[2023-08-09T08:30:42.159+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-09T08:30:42.218+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): accurate> on 2023-08-09 08:30:17.385813+00:00
[2023-08-09T08:30:42.229+0000] {standard_task_runner.py:57} INFO - Started process 2903 to run task
[2023-08-09T08:30:42.240+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'manual__2023-08-09T08:30:17.385813+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp2ggfkbkx']
[2023-08-09T08:30:42.250+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask accurate
[2023-08-09T08:30:42.403+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=manual__2023-08-09T08:30:17.385813+00:00/task_id=accurate permission to 509
[2023-08-09T08:30:42.413+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.accurate manual__2023-08-09T08:30:17.385813+00:00 [running]> on host 0ff7fa45765f
[2023-08-09T08:30:42.666+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='accurate' AIRFLOW_CTX_EXECUTION_DATE='2023-08-09T08:30:17.385813+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-09T08:30:17.385813+00:00'
[2023-08-09T08:30:42.671+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-09T08:30:42.673+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'accurate"]
[2023-08-09T08:30:42.703+0000] {subprocess.py:86} INFO - Output:
[2023-08-09T08:30:42.707+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-08-09T08:30:42.708+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-08-09T08:30:42.709+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-09T08:30:42.739+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-09T08:30:42.749+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=accurate, execution_date=20230809T083017, start_date=20230809T083042, end_date=20230809T083042
[2023-08-09T08:30:42.784+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 17 for task accurate (Bash command failed. The command returned a non-zero exit code 2.; 2903)
[2023-08-09T08:30:42.820+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-09T08:30:42.867+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
