[2023-08-09T08:33:25.766+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=manual__2023-08-09T08:32:51.855261+00:00/task_id=inaccurate permission to 509
[2023-08-09T08:33:26.122+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=manual__2023-08-09T08:32:51.855261+00:00/task_id=inaccurate permission to 509
[2023-08-09T08:33:27.070+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2023-08-09T08:32:51.855261+00:00 [queued]>
[2023-08-09T08:33:27.134+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2023-08-09T08:32:51.855261+00:00 [queued]>
[2023-08-09T08:33:27.143+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-09T08:33:27.252+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): inaccurate> on 2023-08-09 08:32:51.855261+00:00
[2023-08-09T08:33:27.262+0000] {standard_task_runner.py:57} INFO - Started process 2969 to run task
[2023-08-09T08:33:27.286+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2023-08-09T08:32:51.855261+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpumqevgx2']
[2023-08-09T08:33:27.304+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask inaccurate
[2023-08-09T08:33:27.884+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=manual__2023-08-09T08:32:51.855261+00:00/task_id=inaccurate permission to 509
[2023-08-09T08:33:27.908+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.inaccurate manual__2023-08-09T08:32:51.855261+00:00 [running]> on host 0ff7fa45765f
[2023-08-09T08:33:28.706+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-08-09T08:32:51.855261+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-09T08:32:51.855261+00:00'
[2023-08-09T08:33:28.724+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-09T08:33:28.732+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate"]
[2023-08-09T08:33:28.845+0000] {subprocess.py:86} INFO - Output:
[2023-08-09T08:33:28.862+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-08-09T08:33:28.864+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-08-09T08:33:28.877+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-09T08:33:29.043+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-09T08:33:29.068+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=inaccurate, execution_date=20230809T083251, start_date=20230809T083327, end_date=20230809T083329
[2023-08-09T08:33:29.129+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 26 for task inaccurate (Bash command failed. The command returned a non-zero exit code 2.; 2969)
[2023-08-09T08:33:29.247+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-09T08:33:29.588+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
