[2023-09-04T12:41:07.245+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-09-03T00:00:00+00:00/task_id=accurate permission to 509
[2023-09-04T12:41:07.687+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-09-03T00:00:00+00:00/task_id=accurate permission to 509
[2023-09-04T12:41:08.757+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.accurate scheduled__2023-09-03T00:00:00+00:00 [queued]>
[2023-09-04T12:41:08.875+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.accurate scheduled__2023-09-03T00:00:00+00:00 [queued]>
[2023-09-04T12:41:08.889+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-04T12:41:09.139+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): accurate> on 2023-09-03 00:00:00+00:00
[2023-09-04T12:41:09.184+0000] {standard_task_runner.py:57} INFO - Started process 102 to run task
[2023-09-04T12:41:09.207+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2023-09-03T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpl0m8ui3t']
[2023-09-04T12:41:09.227+0000] {standard_task_runner.py:85} INFO - Job 52: Subtask accurate
[2023-09-04T12:41:09.511+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-09-03T00:00:00+00:00/task_id=accurate permission to 509
[2023-09-04T12:41:09.527+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.accurate scheduled__2023-09-03T00:00:00+00:00 [running]> on host 0ff7fa45765f
[2023-09-04T12:41:10.218+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='accurate' AIRFLOW_CTX_EXECUTION_DATE='2023-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-03T00:00:00+00:00'
[2023-09-04T12:41:10.224+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-04T12:41:10.227+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'accurate"]
[2023-09-04T12:41:10.281+0000] {subprocess.py:86} INFO - Output:
[2023-09-04T12:41:10.297+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-04T12:41:10.298+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-04T12:41:10.300+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-04T12:41:10.392+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-04T12:41:10.460+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=accurate, execution_date=20230903T000000, start_date=20230904T124108, end_date=20230904T124110
[2023-09-04T12:41:10.545+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 52 for task accurate (Bash command failed. The command returned a non-zero exit code 2.; 102)
[2023-09-04T12:41:10.622+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-04T12:41:10.760+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
