[2023-09-04T12:40:52.339+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-08-09T00:00:00+00:00/task_id=inaccurate permission to 509
[2023-09-04T12:40:52.907+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-08-09T00:00:00+00:00/task_id=inaccurate permission to 509
[2023-09-04T12:40:54.671+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-08-09T00:00:00+00:00 [queued]>
[2023-09-04T12:40:54.913+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-08-09T00:00:00+00:00 [queued]>
[2023-09-04T12:40:54.949+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-04T12:40:55.286+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): inaccurate> on 2023-08-09 00:00:00+00:00
[2023-09-04T12:40:55.382+0000] {standard_task_runner.py:57} INFO - Started process 96 to run task
[2023-09-04T12:40:55.417+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2023-08-09T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmprs7s_ehg']
[2023-09-04T12:40:55.443+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask inaccurate
[2023-09-04T12:40:56.438+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=my_dag/run_id=scheduled__2023-08-09T00:00:00+00:00/task_id=inaccurate permission to 509
[2023-09-04T12:40:56.523+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2023-08-09T00:00:00+00:00 [running]> on host 0ff7fa45765f
[2023-09-04T12:40:57.832+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-09T00:00:00+00:00'
[2023-09-04T12:40:57.892+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-04T12:40:57.977+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate"]
[2023-09-04T12:40:58.127+0000] {subprocess.py:86} INFO - Output:
[2023-09-04T12:40:58.206+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-04T12:40:58.243+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-04T12:40:58.321+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-04T12:40:58.508+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-04T12:40:58.604+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=inaccurate, execution_date=20230809T000000, start_date=20230904T124054, end_date=20230904T124058
[2023-09-04T12:40:58.862+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 51 for task inaccurate (Bash command failed. The command returned a non-zero exit code 2.; 96)
[2023-09-04T12:40:59.070+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-04T12:40:59.555+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
